File:
    Version: 0.2

    
################################
####### General Settings #######
################################

# <<< Choose which dragon-entities can't destroy blocks >>>
AntiGriefDragons:
    bypassWorldGuardAntiSpawn: true
    ofDragonTravel: false
    all: true

# <<< Choose which messages-file DragonTravel should use >>>
# Possible values are:
# 'en' - English
# 'de' - German
# 'fr' - French
# 'da' - Danish
# 'custom' - leads to the use of the file named "messages-custom.yml"
# Default: 'en'
Language: 'en'
    
# <<< Set the dragon's flying-speed >>>
# The number represents the blocks in 1 server tick, 20 ticks = 1 second
# Do not set it above 1.0 or your server will lag like hell and/or crash!
# Default: 0.5
DragonSpeed: 0.5

# <<< Set the maximum amount of dragons on your server >>>
# Use this if you encounter lags on your server which are caused
# by too many dragons travelling at the same time.
# This only limits DragonTravel-dragons and does not
# handle stationary dragons spawned by DragonTravel!
# Default: 99999 (somehow disabled^^)
DragonLimit: 99999

# <<< Teleport a player who dismounts back to the point he started from >>>
# Some players use flights or travels to a location to "jump off" during the
# flight an that way get to other places.
# If set to true, those players will be teleported back to the point they started from.
# If set to false, those players will just be dismounted where they are and teleported to the ground.
# Default: true
TeleportToStartOnDismount: true

# <<< Toggles vulnerability of players >>>
# If set to true, dragon-riders take damage (players can also be killed by the environment when travelling through mountains!)
# If set to false, dragon-riders do not take damage at all.
# Default: false
VulnerableRiders: false

# <<< Choose the commands which can't be executed while being on a dragon >>>
# Make sure to list all commands which could teleport a player away from the dragon!
# You must only define the first word with the "/", in this list!
CommandPrevent:
- /spawn
- /f
- /kill
- /home
- /tp

# <<< The Random Destination >>>
# When traveling to a destination with this name (Default: _random_) will start a travel
# to a random destination within the borders you can set below.
RandomDest:
    Name: '_random_'
    Limits:
        X-Axis:
            Min: -100
            Max: 100
        Z-Axis:
            Min: -100
            Max: 100
            
# <<< Limit mounting to stations >>>
# You can limit the mounting of dragons to stations (and a specified radius around it)
# Defaults:
#   EnableForTravels: false
#   EnableForFlights: false
#   Radius: 5
#   ExcludeSigns: false
MountingLimit:
    EnableForTravels: false
    EnableForFlights: false
    Radius: 5
    ExcludeSigns: false
            
################################
####### Payment-Settings #######
################################

Payment:
    usePayment: false
    byResources: false
    byEconomy: false
    Economy:
        Prices:
            toStation: 5.0
            toRandom: 5.0
            toPlayer: 5.0
            toCoordinates: 5.0
            toHome: 5.0
            toFactionhome: 5.0
            setHome: 5.0
            Flight: 5.0
    Resources:
        Item: 371
        Prices:
            toStation: 5
            toRandom: 5
            toPlayer: 5
            toCoordinates: 5
            toHome: 5
            toFactionhome: 5
            setHome: 5
            Flight: 5


            
################################            
####### Travel-Settings #######
################################

# <<< Choose how high the dragon flys during a travel >>>
# The number represents blocks Numbers over sky-height are allowed
# Default: 100
TravelHeight: 100

# <<< Does a player need to have a special item in hand to use DragonTravel? >>>
# Choose the item a player needs to have in his hands to use DragonTravel.
# Default: 122 (Dragon-Egg which can be obtained by killing the Enderdragon)     
RequiredItem:
    Item: 122
    For:
        toStation: false
        toRandom: false
        toPlayer: false
        toCoordinates: false
        toFactionhome: false
        toHome: false
        Flight: false
    
# <<< Limit the use of the normal travels to signs >>>
# This disables the command /dt travel for all players with the admin-permissions.
# Default: false
OnlySigns: false

# <<< Default setting for the ptoggle-flag of a player >>>
# Choose whether travels to a player are allowed (true) or denied (false) by default
# Default: true
PToggleDefault: true
